### ISSUE TITLE
add first time connection (unpaired device)

### ISSUE THREAD

**Issue by mat90c** [lwis/miband-notifier#11]
Hi,
if I want to connect mi band the first time without pair it with original mifit app do you know if there is a way? If we add this feature this app can be run standalone without original app.
If you have any suggestions about code, or any other info about how original pairing works in original app please let me know. 
Thank you

**Comment by lwis** [comment]
This has it's difficulties.

Writing 2 to characteristic 0xFF0F will begin the pairing process - the
device will need to be tapped to confirm the process. The band will then
respond with a 2 if the pairing was successful and 0xFFF if it was not.

However! I'm unsure how the MiBand behaves when it's paired, as I believe
it is not discoverable - this could only be when it's connected, when
disconnected it may remain in an unpaired state, you'll have to test.

By writing 1 to 0xFF0D the device will drop all bonding.

Although this isn't the way I'd approach it, as you won't be capturing any
stats from the band.

Disclaimer: I'm not aware if any new firmwares have broken the above.

**Comment by arnottcr** [comment]
It seems like the underlying request in this issue is, you would like to have the functionality of the mi fit app plus notifications, in open source form; let me know if I am wrong. This seems like a laudable goal, but will require vastly more reverse engineering, as currently notification and several other simple operations are working, but a lot of things are missing and unknown.

Overall, adding these features really seems to change the nature of this application and I think you might be best off forking this project if you really want these features. Because recall this new application will need to deal with sleep, steps, fitness, band location, screen unlock, call notification, alarms, and pairing. Furthermore, you may run into issues with firmware updates, as your app will likely only work well with some firmware versions, and unless there is a large reverse engineering breakthrough firmware updates seem like an unattainable feat. [Though, if you can get this working, you may well want to jump to custom firmware.]

note: there have been several firmware updates and my band is now on 1.0.9.14.

**Comment by lwis** [comment]
@arnottcr Agreed, this isn't something I'd be looking to pull into this project. I'd be hesitant in providing bonding options, as the app was never intended to be standalone.

The point about chasing firmware versions is also very important, and frustrating.

**Comment by mat90c** [comment]
I've only asked for add pairing functionally to can run app standalone. Agreed I'm not going to add features like sleep steps etc. I'm only searching information about pairing to find out if it could be done "easly". I'm not going to pull request about standalone options, if you wan't these.

I agreed about firmware updates related issues, and what could be a solution?
If someone only interest use mi band to get notification could don't use mifit original app, and run only this app standalone (and will never incur on firmware updates)

**Comment by chrisvella** [comment]
I agree with @mat90c. This feature would be all that I would need from the current project. Initial configuration, notifications and tasker support should allow me to skip the proprietary application entirely. Not to say the other features wouldn't be nice, but not really vital.

This project is also interesting, and may be more suitable to those more specific features: https://github.com/Freeyourgadget/Gadgetbridge

**Comment by arnottcr** [comment]
Alright, if that is the limit to your request it could be done by hiding a pairing option in an advanced settings menu; but this is out of my scope, so I will let @lwis decide if this is a feature he wants to support.

However, this still does not solve the version islanding issue: if I buy a band it could have any firmware version from the initial one flashed at release to the most recent version. Without a method to reliably update it, and again you want this to not need the mi fit app, this means an application needs to support every versions feature set. Currently they have not broken anything, @lwis could confirm this, with updates but systemic changes are not outside the realm of reasonability. I would describe this as a developers nightmare, and a valid reason to not implement into this feature.

If you are comfortable with only the most recent firmware be supported and this feature really means something to you, submit a pull request.

**Comment by lwis** [comment]
I'm not sure how difficult it might be, but it is possible to write the
firmware to 0xFF08 - this could be used to downgrade/upgrade the version
for standalone users. But yes, supporting multiple versions is not made
easy.

I also agree that this functionality should be in an advanced menu.

**Comment by mat90c** [comment]
@arnottcr leave out the feature I asked about pairing the mi band, when you talk about possible issues related firmware version, as I can imagine, also actual protocols about vibrate and set led on procedures could be changed in future firmware and so could stop working no?

**Comment by lwis** [comment]
@mat90c that is a very possible (albeit unlikely) side effect of a firmware
update.

**Comment by mat90c** [comment]
yes, what I was saying is not only pairing feature will suffer new firmware updates, but also currently features like vibrate and led could. The firmware update is a common problem for all features of this app.

**Comment by arnottcr** [comment]
Currently it looks as though with recent updates they have kept the same protocol, added a few new features [immediate alert], and obfuscated the characteristic names; but yes there is nothing preventing them from vastly changing the protocol or adding encryption/drm that would make an application like this useless.

@mat90c: yes that is something that needs to be maintained, but if one is to support all versions of the firmware the source code will get unwieldy. Also you will need to check firmware version before trying to talk to a client device. Something for which I do not see successful reverse engineering [I may well be wrong].

**Comment by mat90c** [comment]
@arnottcr  Agreed, by now this app is only working with original mifit app, so I think manage all firmware version is useless, the important thing is it works at least with last firmware (my opinion)

**Comment by cpfeiffer** [comment]
Gadgetbridge now has a preliminary discovery and pairing functionality. It's supposed to work completely without the original MiFit app. There will be a new version on F-Droid this weekend, if anyone wants to test it.

FWIW, I'm only testing it with firmware version 1.0.4.2 as I've never used MiFit. If newer firmware versions break the API, the only thing we could (hopefully) provide is a firmware downgrade.
