### ISSUE TITLE
flash duration time

### ISSUE THREAD

**Issue by mat90c** [lwis/miband-notifier#12]
If I set a duration of flash (led) does it works?
Can I turn on led on mi band for 10 seconds or 10 minutes for example (always on) or miband has a maximum timeout after that it turn off automatically led?

**Comment by lwis** [comment]
The implementation for this is weird and less than ideal. I do this by
setting the color (which shows for around 500ms) then turning the colours
off, which means the maximum LED duration is limited by the duration the
band displays a changed colour for.

I hope this makes sense, and the timings of BLE make this very sporadic as
in low energy mode it can have a delay of >500ms. High energy can be as
little as 10ms. Very unpredictable.

**Comment by mat90c** [comment]
I've done some tests.
If I comment out (disable) the next line on code that turn off leds, seems
nothing changes, app works like before. What is it for? I'm talking about
this line

list.add(new WriteAction(MiBandConstants.UUID_CHARACTERISTIC_CONTROL_POINT,
new byte[]{ 14, originalColours[0], originalColours[1], originalColours[2],
(byte) 0 }));




2015-03-26 16:39 GMT+01:00 Lewis Juggins <notifications@github.com>:

> The implementation for this is weird and less than ideal. I do this by
> setting the color (which shows for around 500ms) then turning the colours
> off, which means the maximum LED duration is limited by the duration the
> band displays a changed colour for.
>
> I hope this makes sense, and the timings of BLE make this very sporadic as
> in low energy mode it can have a delay of >500ms. High energy can be as
> little as 10ms. Very unpredictable.
>

**Comment by lwis** [comment]
That line reverts to the LED colour set in the app, and turns the LED off.
