### ISSUE TITLE
Purpose of this app?

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [lwis/miband-notifier#15]
Hi, I am happy to see that there seems to be some development going on for the miband! 

However I cannot seem to understand the purpose of this app here. The readme states that the original xiaomi app needs to be installed in order to use this app. So in what way does it enhance the miband experience? Maybe this could be stated in the readme as well :)

Is the collected data still sent to xiaomi via the original app? I am actually looking for a way to use the miband offline without exposing my data to any company.

**Comment by chrisvella** [comment]
@1337sup3rh4x0r I'm not a developer, but I use the app daily.

The purpose of this app is to allow other application notifications to be sent to your band. The official app does not have this feature (although I think you can install some sort of unofficial patch...). 

There has been discussion about miband notifier handling the connection to the band (why the official app still has to be installed). Concerns about firmware updates are the main issue with this idea. However if you can code a solution, I would be very interested/happy to test!

Miband notifier will not meet your needs if you intend to use it strictly as a fitness tracker. Check this app out: https://github.com/Freeyourgadget/Gadgetbridge They say they intend to add mi band support in the future.

**Comment by 1337sup3rh4x0r** [comment]
Thank you for explaining and hinting me towards gadgetbridge!

I have also found the App OpenBand https://github.com/UgoRaffaele/xiaomi-miband-android by the same author as this app here. Looks promising and I will test.
