### ISSUE TITLE
Can you explain a bit more about tasker integration?

### ISSUE THREAD

**Issue by mengkelee** [lwis/miband-notifier#16]
Can you explain a bit more about tasker integration?  Is it possible to have the 3 led light showing 3 different color at the same time ? Can you choose which light to shine along?

Jeff

**Comment by lwis** [comment]
3 different colours isn't possible, nor can you select which LED is lit.
You are able to choose the vibration/colour, however.

**Comment by mengkelee** [comment]
Cannot install on MI 4. says installation pack error. Is that normal for android 4.4.4?

**Comment by lwis** [comment]
Yes, I build for 5.0, the BLE stack for pre-Lollipop is awful.

**Comment by mengkelee** [comment]
You still working on it? I find the vibration and light duration and
frequency adjustment could be better, right now they have a quite narrow
range and a bit confusing.
2015年5月24日 上午1:56于 "Lewis Juggins" <notifications@github.com>写道：

**Comment by lwis** [comment]
I'm not currently actively working on the project, the settings reflect the inaccuracy caused by the latency and the poor BLE stack Android provides.

**Comment by mengkelee** [comment]
Functionality point of view, it works perfectly. But it would be better if
the flash can repeat more times. If you check the tweaked mi band app with
notify, you will know what I mean about the settings.   Great app after
all, now I can update my mi band official app cause I bought the mi scale
and have the notification pushed.

Cheers,
Mengke
2015年5月24日 上午3:16于 "Lewis Juggins" <notifications@github.com>写道：
