### ISSUE TITLE
Tasker plugin doesnt affect LEDs

### ISSUE THREAD

**Issue by dwean** [lwis/miband-notifier#17]
First of all, thank you so much for this awesome work. Your plugin is probably the main reason I decided to purchased it. I'm running your app on my D855 LG G3 which runs lollipop 5.0.0 currently (v20h). Though when I set app notifications in the app itself the LEDs are working fine, in the Tasker module the LEDs doesnt turn on at all. Tried different colors+ reboot, but it didnt help. Thanks!

**Comment by lwis** [comment]
Hmm, I didn't write that part of the app - nor do I use it. @FernandoWahl
<https://github.com/lwis/miband-notifier/commits/master?author=FernandoWahl>
can
hopefully help you.

**Comment by chowhoundb** [comment]
Tasker plugin is working properly on OnePlus One running 5.1.1 slimlp.

**Comment by lwis** [comment]
Are you able to activate the LED's from the main app?

**Comment by chowhoundb** [comment]
Yes, LEDs activate properly from the main app and the tasker plugin.

**Comment by zbenz** [comment]
On my nexus 4 running 5.1.1 N5Xrom, Mi band notifier main app can trigger vibration & send led color. Custom app notifications also work but the tasker plugin doesn't work. I tried to remove tasker and installe again but it dosen't help. Any good idea? Thanks!
