### ISSUE TITLE
App crash with newest firmware : 1.0.9.55

### ISSUE THREAD

**Issue by Diji23** [lwis/miband-notifier#19]
A new firmware bas been released (see Mi forum). App seems to crash whenever you try to use notification (je. Test vibration). App version that update firmware : 1.4.614 

So I upgraded and notifier doesn't work anyway, and unfortunatly there's noway to downgrade :(

**Comment by KashaMalaga** [comment]
com/xiaomi/hm/bleservice/profile/IMiLiProfile;
com/xiaomi/hm/health/bt/b/v;

Check these two files, 

It seems that they are obfuscating the use of api, using proguard and changing some values in the commands! :P

**Comment by Diji23** [comment]
Was just saying, can't code shit.. lol.

But, how nice of them; they added Notification vibration in the default app. (which only support vibration, no color) and made it available for MIUI only lol. and apparently they're restricting use of API. (according to what you just said). Why would they do that. it's a 15$ device ffs Shooting themselves in the foot.

**Comment by KashaMalaga** [comment]
![lol](https://cloud.githubusercontent.com/assets/879449/7509332/9e89608a-f48f-11e4-8543-384dd87681ed.png)

**Comment by KashaMalaga** [comment]
PS. have to check whatever have changed, no time until weekend :(
https://dl.dropboxusercontent.com/u/31736798/Desktop.rar

**Comment by Diji23** [comment]
No problem, take whatever time you need. And thanks for your help. What is this file ?

(Also, i'd like to start developping apps such as this one, where does one start ? :))

**Comment by KashaMalaga** [comment]
Lewis has made a great example! Its the best beggining, i´ve got my own customized version ;)

**Comment by Diji23** [comment]
Lewis? Who's that. Where can I find his examples  ? =/

**Comment by lwis** [comment]
I'm the maintainer 😉

**Comment by Diji23** [comment]
Oups lol, Hi Lwis :)). 

Thanks by the way.

**Comment by chrisvella** [comment]
I made the mistake of updating. Anything I can do?

**Comment by Diji23** [comment]
As far as I know, there's noway to downgrade the firmware so far... All you van expect os a version that work with newest firmware.

**Comment by chrisvella** [comment]
Yea I thought so. That's really disappointing.
