### ISSUE TITLE
Vibration on nexus 4

### ISSUE THREAD

**Issue by Angelmmiguel** [lwis/miband-notifier#2]
Hello!

I'm testing your app in my Nexus 4. The color of the band changes, but when I click on vibration test, debug console said "Write successful", but my band didn't vibrate. 

I'm newby in reverse engineering on Android. I'm trying to extract the sequence of bytes to start the motor vibration. I found the **COMMAND_STOP_VIBRATE**, but I missed the command to start vibrate. I'm working of this, but, where did you find [8, 2] sequence to start vibrate?

Thanks!. Your project and progress are awesome :)

**Comment by lwis** [comment]
The reverse engineering mainly comes from decompiling the official APK, sometimes the band doesn't respond to writes - it can be somewhat inconsistent, particularly when spammed. 

8,0 starts the motor for 2 vibrates with a green light (IIRC)
8,1 starts the motor for 10 vibrates with a blue light
8,2 starts the motor for two vibrates with no light

19 stops the motor - but as this depends on the BLE param configuration it may be around ~500ms before the band stops, and as mentioned before, sometimes the band ignores the write completely (executing the callback in the Bluetooth stack) but not actioning the write on the device.

**Comment by Angelmmiguel** [comment]
I decompiled the official APK with apktool too. I think 8 byte is the NOTIFY command, so is there any command to start vibrate?

I will retry the test on my nexus. Thanks!
