### ISSUE TITLE
Notification until midnight does not work correctly

### ISSUE THREAD

**Issue by br41n86** [lwis/miband-notifier#21]
I am using 24H time notation and i want my notification from 08:00 until 24:00 (0:00).
The app only allows 12H time notation and the correct setting for 24:00 or 0:00 would be 12 a.m,
but when i set my notification from 8 a.m. until 12 a.m (tested with p.m, too) i dont get any notification for that application. Only work around for now is setting up until 11:59 p.m.

**Comment by br41n86** [comment]
I think i know where the problem is, but i don't know how to fix it.
NotificationService has a function called isInPeriod. If you set endTime to 0:00 it is taking 0:00 from the same day instead from the next day. Would be nice if someone could fix this.

**Comment by lwis** [comment]
Hi,

Please try the latest development release.

**Comment by br41n86** [comment]
I tired, but still no go. I looked through your commit and i thought something like this would be the fix, but i think the SimpleDateFormat needs the day part too or else it is cutting out only Hour and Minutes again or am i wrong?

**Comment by lwis** [comment]
Haha wow, I didn't even consider the condition at the bottom, or my
original logic. Oops.

I'll revisit this again tomorrow.

**Comment by lwis** [comment]
Could you try again for me?

**Comment by br41n86** [comment]
Yes, this one fixes it.
Right now i am looking into your code.
It would be even better to check IF the endTime is smaller then startTime, then set endtime.Date,1.
Only an idea for people who are partying past midnight would be even more usefull.

**Comment by lwis** [comment]
Potential enhancement but original issue has been resolved.
