### ISSUE TITLE
Don't work since MiFit update

### ISSUE THREAD

**Issue by Fullmono** [lwis/miband-notifier#23]
Hi, 
This app don't work anymore since update to "MiFit" app (1.4.XXX). 

FYI, MiFit now allow sync with Google Fit :-) Less work for you...

Thank you for your great work!

**Comment by uglide** [comment]
+1

**Comment by lwis** [comment]
Sadly the app will always be fighting a losing battle with Xiaomi changing
the firmware - this makes it very difficult to always be compatible.

If debug can still be switched on, can someone provide me with some logs
from the official app? Or maybe a decompilation?

I don't have the resource to stay on top of updates, which is why many
users recommend not upgrading the firmware.

**Comment by Fullmono** [comment]
Hi, 
Do you no if there is a way to downgrade the band? 

I will try to get debug but I don't have much time for now.

**Comment by lwis** [comment]
I believe installing an older version will overwrite the firmware version.

**Comment by Fullmono** [comment]
Already tried and it do not work :-/ I will investigate.

**Comment by itsmepetrov** [comment]
Hi, I found an application that supports the latest version of the firmware (1.0.9.65): [FREE](https://play.google.com/store/apps/details?id=com.mc.mibandfree), [FULL](https://play.google.com/store/apps/details?id=com.mc.miband).
Maybe it will be able to decompile the application and see the new API implementation?

**Comment by lwis** [comment]
Hilariously that's a fork of my app. I would appreciate upstream
contributions, but he's seemingly uninterested in that.

**Comment by lwis** [comment]
@mat90c Are you interested in contributing upstream? As I see you're pulling the translations contributed to this repo for your own app?

**Comment by mat90c** [comment]
Hi Lewis,
I have changed probably more than 70% of original source, I'm going to
share a folder where if you like you can download translations as I'm not
using the original translation loaded on the repo (too differences)

2015-06-01 9:15 GMT+02:00 Lewis Juggins <notifications@github.com>:

**Comment by lwis** [comment]
@mat90c I think the users are interested in the firmware compatibility changes, would you be open to contributing those upstream?

**Comment by mat90c** [comment]
Firmware compatibility, as said on older replays, there is not much we can
do as it depend on xiaomi firmware changes. By now we are lucky that things
keep working it seems. Do you have new ideas about that? If I can I'd like
to help you to solve this problem...

2015-06-01 19:56 GMT+02:00 Lewis Juggins <notifications@github.com>:

**Comment by lwis** [comment]
@mat90c The app isn't currently working with the latest firmware, and as Xiaomi disabled debug mode within their app, I'm not sure how to work out what needs to be changed? I've been told that your fork works with the latest firmware?

**Comment by mat90c** [comment]
I'm testing with 1.0.9.65 firmware. You told me, times ago, that you wan't
add a searching feature as you want go straight with mi fit original app so
I've started my project and leaved yours as I need a standalone robust
(compatible with mi fit too) version. I've changed maybe more than 80% of
original source so I can't tell you easily what can be do your problem as I
should study your code and compare with mine. Now I haven't time to develop
your version and mine at the same time, but maybe if you are interested we
could find a solution to work together on one big project if you can spend
time. I don't know what are your plans...

2015-06-01 20:05 GMT+02:00 Lewis Juggins <notifications@github.com>:

**Comment by lwis** [comment]
Have you changed the code so dramatically that the constants class is no
longer maintained? As I intended for that to be the single point of
firmware changes.

If your code is that much different then don't worry, I'll try to figure
out the changes some time soon.
