### ISSUE TITLE
App crashes after adding an app to the list.

### ISSUE THREAD

**Issue by Pitros** [lwis/miband-notifier#3]
On release version whole app crashes instantly after pressing done button when confirming adding app to the list. When I try to open app again it still crashes. But that problem only exist on release version, debug works fine. 

I'm using app on Nexus 4 with custom rom. 

Logs from release version: http://pastebin.com/bqPbxSaq, and from debug: http://pastebin.com/RSFWBbai

**Comment by lwis** [comment]
Hi,

Is this issue still persisting with v0.6-dev release? 

`java.lang.ClassCastException: com.a.a.b.w cannot be cast to com.lewisjuggins.miband.c.a`

Is the cause of the issue, but I've changed (this line)[https://github.com/lwis/miband-notifier/blob/master/src/main/java/com/lewisjuggins/miband/MiOverviewActivity.java#L227] to protect against a bad cast.

As I've only had reports of this issue from custom ROM's I'm curious as to what's different. Which app are you adding to cause the crash?

**Comment by Pitros** [comment]
Yes, I used latest version which was released hour ago.

I tried to add 3 different apps, and any of them results crashes.

**Comment by feroxy** [comment]
I'm on a nexus 5 with rooted stock android 5.0.1, but can confirm the same cast error;

01-18 18:25:05.667 I/ActivityManager(773): Start proc com.lewisjuggins.miband for activity com.lewisjuggins.miband/.MiOverviewActivity: pid=11018 uid=10386 gids={50386, 9997, 3002, 3001} abi=armeabi-v7a
01-18 18:25:05.796 D/AndroidRuntime(11018): Shutting down VM
01-18 18:25:05.797 E/AndroidRuntime(11018): FATAL EXCEPTION: main
01-18 18:25:05.797 E/AndroidRuntime(11018): Process: com.lewisjuggins.miband, PID: 11018
01-18 18:25:05.797 E/AndroidRuntime(11018): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lewisjuggins.miband/com.lewisjuggins.miband.MiOverviewActivity}: java.lang.ClassCastException: com.a.a.b.w cannot be cast to com.lewisjuggins.miband.c.a

 release apk crashes on adding any app and at every attempt to start thereafter (needs data cleared). The debug apk actually works without crashing for me though. It will activate the lights on the band in the chosen colour, but will not vibrate.

**Comment by buneech** [comment]
Same as feroxy, only I have a Nexus 4 with stock unrooted 5.0.1.
Release version crashes when adding an app.
Debug version doesn't crash when adding an app, vibrate doesn't work, test vibrate also doesn't work, but lights do work when I get a notification.

Log from release version:
```
I/ActivityManager(  559): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.lewisjuggins.miband/.MiOverviewActivity (has extras)} from uid 10139 on display 0
I/ActivityManager(  559): Start proc com.lewisjuggins.miband for activity com.lewisjuggins.miband/.MiOverviewActivity: pid=6566 uid=10161 gids={50161, 9997, 3002, 3001} abi=armeabi-v7a
D/AndroidRuntime( 6566): Shutting down VM
E/AndroidRuntime( 6566): FATAL EXCEPTION: main
E/AndroidRuntime( 6566): Process: com.lewisjuggins.miband, PID: 6566
E/AndroidRuntime( 6566): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lewisjuggins.miband/com.lewisjuggins.miband.MiOverviewActivity}: java.lang.ClassCastException: com.a.a.b.w cannot be cast to com.lewisjuggins.miband.c.a
E/AndroidRuntime( 6566):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
E/AndroidRuntime( 6566):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
E/AndroidRuntime( 6566):        at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 6566):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime( 6566):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6566):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6566):        at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 6566):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6566):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6566):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 6566):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime( 6566): Caused by: java.lang.ClassCastException: com.a.a.b.w cannot be cast to com.lewisjuggins.miband.c.a
E/AndroidRuntime( 6566):        at com.lewisjuggins.miband.MiOverviewActivity.onCreate(Unknown Source)
E/AndroidRuntime( 6566):        at android.app.Activity.performCreate(Activity.java:5933)
E/AndroidRuntime( 6566):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime( 6566):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
E/AndroidRuntime( 6566):        ... 10 more
W/ActivityManager(  559):   Force finishing activity com.lewisjuggins.miband/.MiOverviewActivity
I/OpenGLRenderer(  559): Initialized EGL, version 1.4
W/ActivityManager(  559): Activity pause timeout for ActivityRecord{2e4ac247 u0com.lewisjuggins.miband/.MiOverviewActivity t3094 f}
W/CursorWrapperInner( 5469): Cursor finalized without prior close()
D/TaskPersister(  559): removeObsoleteFile: deleting file=3093_task.xml
D/TaskPersister(  559): removeObsoleteFile: deleting file=3093_task_thumbnail.png
I/Process ( 6566): Sending signal. PID: 6566 SIG: 9
W/InputMethodManagerService(  559): Window already focused, ignoring focus gainof: com.android.internal.view.IInputMethodClient$Stub$Proxy@41f1021 attribute=null, token = android.os.BinderProxy@373cefc6
I/ActivityManager(  559): Process com.lewisjuggins.miband (pid 6566) has died
W/ActivityManager(  559): Scheduling restart of crashed service com.lewisjuggins.miband/.MiBandCommunicationService in 15864ms
D/HeadsetStateMachine( 5655): Disconnected process message: 10, size: 0
```

**Comment by lwis** [comment]
I've got a feeling this is ProGuard issue, as it's obfuscating the code and clearly causing a problem.

**Comment by paulgavrikov** [comment]
That is proguard for sure

**Comment by lwis** [comment]
I think the class clash is between, I think it's because I have a class named 'Application' which is somehow clashing with the built in Application class.

It's pretty poor for ProGuard to cause this issue.

**Comment by lwis** [comment]
Latest build no longer minifys the code, sorry for the delay.
