### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by flyingrub** [lwis/miband-notifier#32]
Plugin is too old.
I can't launch the build.

**Comment by lwis** [comment]
Which plugin?

**Comment by flyingrub** [comment]
It doesn't say which one.
But your gradle seems cluttered up.
Every one i worked with didn't look like this one...
https://github.com/holylobster/nuntius-android/blob/master/app/build.gradle for exemple.

**Comment by lwis** [comment]
Fixed by 9192266545352003aae880f196beb90aadc1cb0a
