### ISSUE TITLE
inconsistent lighting

### ISSUE THREAD

**Issue by arnottcr** [lwis/miband-notifier#6]
Most of the time when I get notifications from my email client the band vibrates and blinks as expected, however sometimes I just get vibrations. Let me know what kind of logging or information will help to debug this issue; I am familiar with android logging, but not bluetooth logging.

**Comment by lwis** [comment]
This really depends on which mode the band is in, if it's in a low latency mode then it'll respond correctly - if not then the latency can be huge. There's not much I can do about this without killing the battery life of the band, sorry.
