### ISSUE TITLE
UUID_CHARACTERISTIC_CONTROL_POINT is ineffective

### ISSUE THREAD

**Issue by sunwayking** [lwis/miband-notifier#7]
I've tried vibrate() and setColor(), but it didn't work.
It seems like UUID_CHARACTERISTIC_CONTROL_POINT is ineffective.

**Comment by lwis** [comment]
It sounds like a firmware update has changed things, unfortunately I can't guarantee my code will work forever.

If you're comfortable, please put the official MiBand app in debug mode and watch logcat for the connection UUID's. Or use apkgold to decompile the app and pull the UUID's out that way.

**Comment by o15a3d4l11s2** [comment]
I am also interested in the changes that Xiaomi introduced with the latest firmware update. I am writing an applications for iOS, but unfortunately no results with these commands.
